### ISSUE TITLE
Не выполняются некоторые важные тайминги из документации

### ISSUE THREAD

**Issue by Konf** [Konf/ADC_Interface#5]
например t2
Тут стоит сказать что чтобы получить правильную времянку согласно даташиту надо сделать так чтобы наш модуль выставлял и считывал данные по положительному фронту SCLK, а модулируемый модуль ацп делал это по отрицательным фронтам. 
Стоит заметить,что модуль ацп на самом деле вставляет 15 информационых бит а перед ними про отрицательному фронту CS начальный 0. По этому наш модуль должен принимать только 15 бит, а в симуляцию ацп надо добавить выставление нуля и переход в 3 состояние.

**Comment by Konf** [comment]
в fe19dbf частично исправлено, но не уверен, что всё.

**Comment by OlmerAod** [comment]
Так открой даташит и проверь времянку
20 нояб. 2015 г. 19:46 пользователь "Konf" <notifications@github.com>
написал:

**Comment by OlmerAod** [comment]
Из-за того что модель ацп в тестбенчем не может претендовать на полностью
достоверную.
20 нояб. 2015 г. 19:48 пользователь "Александр Силантьев" <
olmer.aod@gmail.com> написал:

**Comment by Konf** [comment]
Смущает конкретно вот что: в даташите на диаграмме между последним фронтом SCLK и фронтом CS есть задержка. Однако нигде не указано (или я не вижу) того, что она важна.
![default](https://cloud.githubusercontent.com/assets/7103182/11306021/a85b6190-8fc0-11e5-8ab6-26f91d12e0e0.PNG)

**Comment by OlmerAod** [comment]
Указана это t11, считается от отрицательного фронта sclk
20 нояб. 2015 г. 19:55 пользователь "Konf" <notifications@github.com>
написал:

**Comment by Konf** [comment]
Там она указана минимально 20нс. При работе схемы на 20МГц SCLK в полупериод 25нс, проходящий у меня от спада SCLK до фронта CS, влезает. Значит этому требованию соответствует. Сейчас проверю ещё раз остальные.
